version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - rabbitmq